main: de.jeff_media.AngelChestAPIExample.ExamplePlugin
name: AngelChestAPIExample
version: 0.0.1-SNAPSHOT
api-version: 1.13
description: An example plugin to show how to use the AngelChestAPI
author: mfnalex
database: false
softdepend: [AngelChest]
commands:
  angelchesttest: